version: '3'

services:
  campaigns_webapp:
    build: webapp
    command: gunicorn --workers=8 --bind=0.0.0.0:8000 webapp.wsgi
    ports:
      - '8000:8000'
    links:
      - 'campaigns_postgress'
  campaigns_postgress:
    image: postgres:12.3
    environment:
      POSTGRES_DB: campaigns_webapp
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ognajd

