version: '3'

services:
  campaigns_webapp:
    build: webapp
    command: gunicorn --workers=8 --bind=0.0.0.0:8000 webapp.wsgi
  campaigns_postgress:
    image: postgres:12.3
    environment:
      POSTGRES_DB: campaigns_webapp
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ognajd
  campaigns_nginx:
    build: nginx
    ports:
      - '80:80'
  campaigns_cache:
    image: memcached:1.6.6
