# Generated by Django 3.0.6 on 2020-05-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('period', models.PositiveSmallIntegerField(db_index=True)),
                ('click_id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('banner_id', models.PositiveIntegerField(db_index=True)),
                ('campaign_id', models.PositiveIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveSmallIntegerField(db_index=True)),
                ('banner_id', models.PositiveIntegerField(db_index=True)),
                ('campaign_id', models.PositiveIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('period', models.PositiveSmallIntegerField(db_index=True)),
                ('conversion_id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('revenue', models.FloatField()),
                ('click_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.Click')),
            ],
        ),
    ]
